<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Skeleton.SharedKernel\Skeleton.SharedKernel.csproj" />
    <ProjectReference Include="..\Skeleton.Modules.Sample.Contracts\Skeleton.Modules.Sample.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
  </ItemGroup>

</Project>
